
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace Donios.SimpleContent.Data
{
    /// <summary>
    /// The DataContext manager class for the MonkeyLinc_Master database.
    /// </summary>
    public partial class DataContextPublished
    {
        
        private Donios.SimpleContent.Data.Managers.Published.MonkeyLincMasterDataManager _manager = null;
        
        /// <summary>
        /// Gets the data manager.
        /// </summary>
        /// <value>The data manager.</value>
        public Donios.SimpleContent.Data.Managers.Published.MonkeyLincMasterDataManager Manager
        {
            get
            {
                if (_manager == null)
                    _manager = new Donios.SimpleContent.Data.Managers.Published.MonkeyLincMasterDataManager(this);
                return _manager;
            }
        }
    }
}